# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Live from my brain with some lag
email: from-my-blog@ledez.net
description: > # this means to ignore newlines until "baseurl:"
  Pense-bête & Todos
  Ruby, Python, devops, Linux, Raspberry π, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jekyll.ledez.net/" # the base hostname & protocol for your site
twitter_username: nledez
github_username:  nledez

# Build settings
markdown: kramdown
