# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# gems: [jekyll-paginate]

# Site settings
title: Live from my brain with some lag
name: Nicolas Ledez
email: from-my-blog@ledez.net
description: > # this means to ignore newlines until "baseurl:"
  Pense-bête & Todos
  Ruby, Python, devops, Linux, Raspberry π, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jekyll.ledez.net" # the base hostname & protocol for your site
disqusid: blog-ledez
twitter_username: nledez
github_username:  nledez

paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
# highlighter: pygments

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty
