# Welcome to Jekyll!
plugins:
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-youtube

# the base hostname & protocol for your site
url: "https://blog.ledez.net"

# Site settings
title: Live from my brain with some lag
name: Nicolas Ledez
email: from-my-blog-xieS3@ledez.net
description: > # this means to ignore newlines until "baseurl:"
  Pense-bête & Todos
  Ruby, Python, devops, Linux, Raspberry π, ...
baseurl: "" # the subpath of your site, e.g. /blog
disqusid: blog-ledez
twitter_username: nledez
github_username:  nledez

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md
  - _images_source

sass:
  style: compressed

flickr:
  api_key: f45ad84fc21f101ecb9f6b9ffb3e7d6f

paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
# highlighter: pygments

category_archive:
  path: category
  slugify: true

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty
